auto-run feature added.
ahmetb/kubectl-allctx pull request #1
Opened 2022-07-09 11:06 UTC by furkanpehli1

Added `--auto` argument to run cmd args automatically.

Waiting for your comments :)

2022-07-09 20:09 UTC, ahmetb commented
Doesn't make sense to me. Empty regex already runs on all + what's automatic here.

2022-07-09 20:24 UTC, furkanpehli1 commented
It is just for bypassing `Continue? [Y/n]:` question like `--auto-approve` in terraform apply/destroy.

2022-07-09 20:29 UTC, ahmetb commented
There's an env var for that. It's not documented yet. You can also bypass that by piping "yes|" to it. 

I'd be open to -q for bypassing the prompt.

2022-07-09 20:38 UTC, furkanpehli1 commented
Yeah I'm aware there is env var but that would be pretty if there  be option like `-q` like you mentioned. If you are open to it I can make some changes on my PR.

2022-07-09 21:25 UTC, furkanpehli1 commented
Due to feedback, changes have made. I'm extremely open to new reviews :)

2022-07-11 18:40 UTC, ahmetb commented
Looks good. You can reopen if you want.

2022-07-11 23:17 UTC, ahmetb requested changes
Overall looks good. Cosmetics feedback.

2022-07-11 23:17 UTC, ahmetb commented on README.md
> +# Bypass prompt with using '-q' flag
You can remove this from here. -h shows it anyway

2022-07-11 23:17 UTC, ahmetb commented on main.go
> +	quiet   = flag.Bool("q", false, "bypasses prompt")
accept confirmation prompts

2022-07-12 06:07 UTC, furkanpehli1 commented on main.go
> +	fmt.Fprintf(os.Stderr, "%s", red("error: "))
I was getting following warning from go-staticcheck on my ide;

`printf-style function with dynamic format string and no further arguments should use print-style function instead (SA1006)`

So I applied what [documentation](https://staticcheck.io/docs/checks#SA1006) says. After all it's just a linter warning and not a big deal. If you want I can revert it to the original.

2022-07-20 15:42 UTC, merged

2022-08-13 06:55 UTC, ahmetb commented on main.go
> +	fmt.Fprintf(os.Stderr, "%s", red("error: "))
I merged this but realized you don't even use the `msg` here. Consider installing a linter to your editor.